#!/usr/bin/env python3
"""Embed offline UI and the source-built, pinned QNX RAM runner."""
import hashlib
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
def generate():
    output=ROOT/'generated';output.mkdir(exist_ok=True)
    page=(ROOT/'web/index.html').read_text().replace('/*__CSS__*/',(ROOT/'web/style.css').read_text()).replace('/*__JS__*/',(ROOT/'web/app.js').read_text())
    (output/'manager_page.h').write_text('// Generated by scripts/generate.py\nstatic const char index_page[]=\n'+''.join(json.dumps(line)+'\n' for line in page.splitlines(keepends=True))+';\n')
    blob=(ROOT/'assets/sd-runner.so').read_bytes();digest=hashlib.sha256(blob).hexdigest()
    expected=json.loads((ROOT/'assets/runner.json').read_text())
    assert digest==expected['sha256'],'Runner changed: rebuild and update provenance before embedding'
    for name,source_hash in expected['sources'].items():
        assert hashlib.sha256((ROOT/name).read_bytes()).hexdigest()==source_hash,'Runner source changed; rebuild the runner asset'
    path='/payload/sd-runner-'+digest[:16]+'.so'
    (output/'manager_asset.h').write_text('#pragma once\n#define MANAGER_RUNNER_PATH '+json.dumps(path)+'\n#define MANAGER_RUNNER_ID '+json.dumps(digest[:16])+'\n')
    data=['#include "payload.h"','static const uint8_t runner[]={']
    data += [','.join(str(x) for x in blob[o:o+32])+',' for o in range(0,len(blob),32)]
    data += ['};','const struct payload_asset payload_assets[]={','{'+json.dumps(path)+',"application/octet-stream",runner,sizeof(runner)},','};','const size_t payload_asset_count=1;']
    (output/'payload.c').write_text('\n'.join(data)+'\n')
    (output/'index.html').write_text(page)
if __name__=='__main__':generate()
